### ISSUE TITLE
No loop in drawHorizontal

### ISSUE THREAD

**Issue by CoXier** [vivian8725118/TimeLine#1]
Class : `ItemDecoration`  and `ItemDecoration2`.
Method: `drawHorizontal`.

For `ItemDecoration`,there is no need for loop.

```java
       verticalLine.setBounds(parentWidth / 2 - 1, top, parentWidth / 2 + 1,bottom);
       verticalLine.draw(c);
```

For `ItemDecoration2` ,just get last child and then draw vertical line only once:

```java
        View lastChild = parent.getChildAt(childCount - 1);
        verticalLine.setBounds(parentWidth / 2 - 1, top, parentWidth / 2 + 1, lastChild.getBottom());
        verticalLine.draw(c);
```

**Comment by CoXier** [comment]
Your idea is awesome.However I think you should take care about your code style and then it's better to use English to comment and write README.

**Comment by vivian8725118** [comment]
thanks
