### ISSUE TITLE
数据量为1的时候会发生错误

### ISSUE THREAD

**Issue by mCyp** [vivian8725118/TimeLine#13]
hi,
当数据量为1的时候，代码是存在问题的
```
if (i == childCount - 1) {
       View lastChild = parent.getChildAt(i - 1); // 这边的i-1就等于-1了
}
```
还有，Dot的radius等于4的时候锯齿就很明显了

**Comment by lhwaizhu** [comment]
> hi,
> 当数据量为1的时候，代码是存在问题的
> 
> ```
> if (i == childCount - 1) {
>        View lastChild = parent.getChildAt(i - 1); // 这边的i-1就等于-1了
> }
> ```
> 还有，Dot的radius等于4的时候锯齿就很明显了

请教下 如何解决 数量为1的情况？

**Comment by mCyp** [comment]
```
View lastChild = parent.getChildAt(i - 1);
// 加这一行代码
 if (null == lastChild) lastChild = child;
```
不过你需要把源码下载下来，然后修改一下源码

> > hi,
> > 当数据量为1的时候，代码是存在问题的
> > ```
> > if (i == childCount - 1) {
> >        View lastChild = parent.getChildAt(i - 1); // 这边的i-1就等于-1了
> > }
> > ```
> > 还有，Dot的radius等于4的时候锯齿就很明显了
> 
> 请教下 如何解决 数量为1的情况？
