### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by wangguifa** [vivian8725118/TimeLine#3]
我想问下，怎么判断瀑布流的item在左边，感觉根据奇偶判断好像不对额，谢谢

**Comment by vivian8725118** [comment]
如果想指定放在哪边，可以给item的类里加一个左右位置的属性，adapter里边根据这个值判断是放那边

**Comment by wangguifa** [comment]
不是想指定放哪边，是因为现在有时间轴+瀑布流的需求，用你写的这个，发现点的位置好像不太对，如果左右两边item长度差很多，左右就不一样了

**Comment by vivian8725118** [comment]
好的，我发现了，等我改下

**Comment by wangguifa** [comment]
方便价格好友吗？还有点问题想咨询下

**Comment by vivian8725118** [comment]
加我qq，1354458047

**Comment by Microhx** [comment]
请原谅我中文不是很好，这个problem我刚解决了，但是也不可以使用adapter中添加属性那么简单，我说一说我的解决方法吧：

我这是这个做的啊，我是在getItemOffset中去判断它是left还是right的，因为对于StaggeredGridLayoutManager中它是有n个Span做count和layout的，判断哪一个span的最小值，就在哪里进行动态添加的。这个你可以review这个code。

` StaggeredGridLayoutManager.LayoutParams params = (StaggeredGridLayoutManager.LayoutParams) view.getLayoutParams();
        int index = params.getSpanIndex();

        if(index == 0) {  //is on your left 
            view.setBackgroundResource(R.drawable.pop_left);
        }else {  //is on your right 
            view.setBackgroundResource(R.drawable.pop_right);
        }
//this code can replace your code in your adapters,  one more time , setting datas in adapter may not have influence`

刚入门Android不是很久，还有中文表达不是很好，I am sorry ...

**Comment by vivian8725118** [comment]
@Microhx 我昨天也是这样改了😀
