### ISSUE TITLE
英语不好，能有汉语版的介绍吗？

### ISSUE THREAD

**Issue by qq1540638878** [vivian8725118/TimeLine#7]
学霸好，我是学渣，我英语不好，代码太烂。这个项目确实不错，正好能用上。不过能不能写点汉语版的介绍，毕竟都是中国人。谢谢了！
加上中文注释就更好了，可以好好学习一下美女的代码了，跪求。

**Comment by vivian8725118** [comment]
好的，稍后我写一个中文版

**Comment by vivian8725118** [comment]
中文版已经加上了
